### ISSUE TITLE
how to send a query to twint-distributed / docker-compose

### ISSUE THREAD

**Issue by ghost** [markowanga/twint-distributed#1]
Hi,

Hope you are all well !

I contribute to the twint project ([twint-docker](https://github.com/twintproject/twint-docker) and [twint-search](https://github.com/twintproject/twint-search)), and I know that the repository is still in WIP, but I am interested by your work.

Could you provide more guidance about how to use your project ?
I tried the docker-compose and it is not working. (saw many things have been commeneted)

Let me updated about your progress as I think it could be suggested as an official addon to twintproject at some point.

Cheers,
X

**Comment by markowanga** [comment]
These weekend I will prepare documentation for API. I will use the swagger api to these, so it could be easy to call.

**Comment by ghost** [comment]
nie ma sprawy po chekame :-)

**Comment by markowanga** [comment]
Sorry, I have updated the system architecture -- now it allow do next steps automatically after finish scrapping. I gave up from swagger api, I will add Wiki in asap.

**Comment by ghost** [comment]
awesome, waiting for it to give a try

**Comment by ghost** [comment]
Any updates mate ? I d like to try it for some experiments.

**Comment by markowanga** [comment]
I put the client classes (to add scrapping tasks and get scrapped data) to directory `./client/`. It's python client -- I have not prepared documentation yet. If you want to call requests from other app it will be easy to get request details from code.

Good luck ;)

**Comment by ghost** [comment]
Hi,

I tried this morning and I have the following error:

```bash
scrapper_consumer_1  | ERROR:pika.adapters.utils.connection_workflow:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: timeout("TCP connection attempt timed out: '192.168.0.124'/(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.124', 5672))")
scrapper_consumer_1  | ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: timeout("TCP connection attempt timed out: '192.168.0.124'/(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.124', 5672))"); first exception - None.
scrapper_consumer_1  | ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: timeout("TCP connection attempt timed out: '192.168.0.124'/(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.124', 5672))"); first exception - None
scrapper_consumer_1  | ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: timeout("TCP connection attempt timed out: '192.168.0.124'/(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.124', 5672))"); first exception - None
scrapper_consumer_1  | ERROR:pika.adapters.blocking_connection:Error in _create_connection().
scrapper_consumer_1  | Traceback (most recent call last):
scrapper_consumer_1  |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
scrapper_consumer_1  |     raise self._reap_last_connection_workflow_error(error)
scrapper_consumer_1  | pika.exceptions.AMQPConnectionError
scrapper_consumer_1  | 2020-05-14 08:33:39,998 [command_server                ] INFO     error during connect to rabbitMQ
scrapper_consumer_1  | 2020-05-14 08:33:39,998 [command_server                ] INFO     wait 3 seconds for next try
command_server_1     | 2020-05-14 08:33:42,663 [command_server                ] INFO     error during connect to mysql
command_server_1     | 2020-05-14 08:33:42,663 [command_server                ] INFO     wait 3 seconds for next try
command_server_1     | 2020-05-14 08:33:45,667 [command_server                ] INFO     error during connect to mysql
command_server_1     | 2020-05-14 08:33:45,667 [command_server                ] INFO     wait 3 seconds for next try
```

Can you share at least the endpoint to call to launch the scraper plz ?

Thanks in advance for your time on replying to these issues.

X.

**Comment by markowanga** [comment]
You should change the host addresses (I put my local) -- the shortest way is put everywhere your local IP address.
Later I will create universal docker-compose

**Comment by ghost** [comment]
I ll wait for this universal docker-compose then. The author of twint said that your repo is really really interesting. I ll update him when it s gonna be operational.

**Comment by markowanga** [comment]
#3
