### ISSUE TITLE
tried to scrape a search but consumer is not working

### ISSUE THREAD

**Issue by ghost** [markowanga/twint-distributed#3]
Hi,

Hope you are all well !

I tried the latest version of twint-distributed and used the /add_search_to_scrap endpoint but it is not scraping the tweets.

Parameters:
- to_search: arxiv
- queue_name: arxiv
- scrap_series: publications
- interval_type: year

Is there something wrong that I am doing ? Is rabbitmq working ?

Thanks for your inputs on that topic as I am really interested by your work.

Cheers,
X

**Comment by markowanga** [comment]
Hi, sorry for long response -- I have many problems with twint. I decided to prepare my library to scrapping tweets. It's https://github.com/markowanga/stweet -- now it is WIP, but it will be ready as soon as possible.

**Comment by markowanga** [comment]
Library is working fast and now I do not envisage a new solution, but when it will be popular i will prepare distributed version for scrap management.
